[package]
name = "bevy_plotters_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.0"
plotters = "0.3.5"

[profile.dev]
opt-level = 1

